baseURL = "https://rationalgrowth.netlify.com"
disqusShortname = ""
googleAnalytics = ""
paginate = "3"
summaryLength = "15"
theme = "bigspring-light"
title = "Rational Growth"
[markup.goldmark.renderer]
unsafe = true
